### ISSUE TITLE
Vite manifest not found

### ISSUE THREAD

**Issue by Klaasc7** [lwekuiper/statamic-activecampaign#1]
When I install the plugin with composer I get a 'Vite manifest not found at' error. After I build the assets manually, my ActiveCampaign lists/tags don't load on the settings page.

**Comment by lwekuiper** [comment]
Have you set your ActiveCampaign API Key and URL in your `.env` file?

**Comment by Klaasc7** [comment]
Yes I did

**Comment by lwekuiper** [comment]
Will need some more details here. Is there an error in the `storage/log/laravel.log` file or in the browser console?

**Comment by Klaasc7** [comment]
Only this:

[previous exception] [object] (Illuminate\\Foundation\\ViteManifestNotFoundException(code: 0): Vite manifest not found at: /Users/xxx/public/vendor/statamic-activecampaign/build/manifest.json at /xxx/vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:728)
[stacktrace]

**Comment by Klaasc7** [comment]
It looks like the dist/build is missing

**Comment by lwekuiper** [comment]
Yes, seems like I need to publish the compiled assets. Will let you know asap.

**Comment by lwekuiper** [comment]
Just released `v1.0.1` with the published assets. Try running `composer update lwekuiper/statamic-activecampaign` to update the dependency. Let me know if any issues.

**Comment by Klaasc7** [comment]
Yes, now it works. Thank you :)
